#!/usr/bin/perl -w
if ($ARGV[0] eq "-h"){
  print "-r       run\n-m       manpage\n-u       check for updates\n";
}
elsif ($ARGV[0] eq "-r"){
  system("/usr/local/bin/lexi.rb");
}
elsif ($ARGV[0] eq "-m"){
  system("man /usr/local/bin/lexi.1");
}
elsif ($ARGV[0] eq "-u"){
  system("sh /usr/local/bin/up.sh");
}
else{
  print "-r       run\n-m       manpage\n-u       check for updates\n";
}
